### PR TITLE
feat: automatically update item status

### PR DESCRIPTION
**Pull request by filoozom**
I've confirmed that it correctly updates the `items` from `useMarketplaceItems`, but it doesn't seem to update the UI. Maybe @vojtechsimetka has more insight regarding that?

This also fixes side effects when `useMarketplaceItems` was called multiple times. This issue might not have manifested itself in the past as `wakuItems.lastUpdate` and `chainItems.lastUpdate` didn't update without doing a whole refresh (e.g. different marketplace).

### CODE REVIEW

**Review by vojtechsimetka — APPROVED** [review]
> I've confirmed that it correctly updates the `items` from `useMarketplaceItems`, but it doesn't seem to update the UI. Maybe @vojtechsimetka has more insight regarding that?

Did you check this in the UI component? My thinking is that maybe the event gets called but the app state does not change and hence the re-render is not triggered.

**Comment by filoozom** [comment]
> Did you check this in the UI component? My thinking is that maybe the event gets called but the app state does not change and hence the re-render is not triggered.

I had a quick look but figured that this is your domain so I'd let you check that out... 😅  I can do it if you want though.

**Comment by vojtechsimetka** [comment]
Not sure I get to it today but tomorrow morning I will.

**Comment by vojtechsimetka** [comment]
So this actually works for me but only for the payout event. I have suspicion that the funding event does not trigger this.

**Comment by filoozom** [comment]
Funding event fixed in https://github.com/swarmcity/boardwalk-contracts/commit/7a66c5c50e7115fb4819e43d90a08486c03df45a

**Comment by filoozom** [comment]
@vojtechsimetka so actually it works on the item list, but not on one specific item, because that uses `useMarketplaceItem` which doesn't follow the events. I'm going to open a separate PR for that.

**Comment by filoozom** [comment]
Actually I just pushed it here: https://github.com/swarmcity/boardwalk-ts/commit/1587b20caef2bfde51398b15294e44add62925f3

**Pull request merged**
